//
//  ClipboardPasteboardReader.swift
//  boringNotch
//
//  Created by Catalin Niculescu on 2026-09-25.
//

import AppKit

/// Image data read from the pasteboard, always as PNG.
struct ClipboardImageData {
    let png: Data
    let pixelWidth: Int
    let pixelHeight: Int
}

/// Reads a pasteboard into one history entry. Called off the main thread.
enum ClipboardPasteboardReader {
    enum Result {
        case content(ClipboardItem.Content)
        case image(ClipboardImageData)
        case skipped
        case denied
    }

    /// Password managers and similar apps mark secrets with these (nspasteboard.org conventions).
    static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]
    /// Image types in order of preference; anything but PNG is converted to PNG.
    static let imageTypes: [NSPasteboard.PasteboardType] = [
        .png,
        .tiff,
        NSPasteboard.PasteboardType("public.jpeg"),
        NSPasteboard.PasteboardType("public.heic")
    ]
    static let maxTextLength = 500_000
    /// Largest PNG kept, and largest source image (e.g. an uncompressed TIFF) read for conversion.
    static let maxImageBytes = 16 * 1024 * 1024
    static let maxSourceImageBytes = 64 * 1024 * 1024

    static func read(_ pasteboard: NSPasteboard) -> Result {
        if #available(macOS 15.4, *), pasteboard.accessBehavior == .alwaysDeny {
            return .denied
        }
        let types = pasteboard.types ?? []
        if types.contains(where: ignoredTypes.contains) {
            return .skipped
        }
        // Files first: a Finder copy also carries the file names as text.
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            return .content(.files(urls))
        }
        // An image wins over text that's only a link (a browser's Copy Image also
        // carries the image URL), but not over real text: copied spreadsheet cells
        // or slides carry a rendered picture of themselves too.
        let text = pasteboard.string(forType: .string)
        let hasText = text.map { !$0.allSatisfy(\.isWhitespace) } ?? false
        if !hasText || text.map(isLink) == true, let image = imageData(from: pasteboard, types: types) {
            return .image(image)
        }
        if let text, hasText, text.utf16.count <= maxTextLength {
            return .content(.text(text))
        }
        return .skipped
    }

    static func imageData(from pasteboard: NSPasteboard, types: [NSPasteboard.PasteboardType]) -> ClipboardImageData? {
        guard let type = imageTypes.first(where: types.contains),
              let source = pasteboard.data(forType: type),
              source.count <= (type == .png ? maxImageBytes : maxSourceImageBytes),
              let rep = NSBitmapImageRep(data: source),
              rep.pixelsWide > 0, rep.pixelsHigh > 0
        else {
            return nil
        }
        let png = type == .png ? source : rep.representation(using: .png, properties: [:])
        guard let png, png.count <= maxImageBytes else {
            return nil
        }
        return ClipboardImageData(png: png, pixelWidth: rep.pixelsWide, pixelHeight: rep.pixelsHigh)
    }

    private static func isLink(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        return !trimmed.contains(where: \.isWhitespace)
            && (trimmed.hasPrefix("http://") || trimmed.hasPrefix("https://"))
    }
}
